### ISSUE TITLE
"Load save" control dialog is shown even when no save is present

### ISSUE THREAD

**Issue by rjoken** [suicvne/DOR_Remake#3]
![Screenshot](https://user-images.githubusercontent.com/17675149/118049410-99ee2a00-b375-11eb-817c-747d55f7a9d0.png)

Minor visual bug where navigating away from "create new save" in save menu changes control dialog to "load save" even if no save is present. Controls still function as normal otherwise.

Additional information:
Client version: 0.6.8.1 win x86_64
OS: Windows 7 Ultimate x86_64
Specs: Ryzen 5 1400, nVidia GTX 950, 32gb ram blah

**Comment by rjoken** [comment]
Maybe this is platform specific. I didn't see this problem in one of your videos and I'm having trouble with a _lot_ of things.

**Comment by suicvne** [comment]
There was a disconnect between the update of the UI Hints component and the UpdateSelection method. The method gets passed an index value and the method clamps between 0 & listItems.Count - 1. 

If the UISaveLoadManager has "EnableCreateSave" checked and the index is 0, it sets the tooltip to say "Create New Save" instead of "Load Save". Well, that code was using the index passed an argument, (which is -1, since you tried to navigate down or navigated up while at the top) not the clamped value (0). 



Issue has now been fixed and will be marked as closed when the new version is posted on itch.
