### ISSUE TITLE
Resolution selector shows many duplicate options

### ISSUE THREAD

**Issue by rjoken** [suicvne/DOR_Remake#5]
![image](https://user-images.githubusercontent.com/17675149/118378995-50008080-b5cf-11eb-9e90-ca6aacee8261.png)
[Player.log](https://github.com/suicvne/DOR_Remake/files/6488296/Player.log)

Resolution selector shows many duplicate options (5 of each)

Additional information:
Client version: 0.6.8.2a win x86_64
OS: Windows 7 Ultimate x86_64
Specs: Ryzen 5 1400, nVidia GTX 950, 32gb ram

**Comment by suicvne** [comment]
Ah, that's definitely a Windows quirk I didnt account for.

**Comment by suicvne** [comment]
I was unable to replicate on the following platform:

0.6.8.2a win x86_64
Windows 10 64bit
Intel Core i7 3770, Radeon RX580 8gb, 24gb ram

This is *technically* a Unity/nvidia driver bug then I think. Nonetheless, I'm skipping over duplicate values if they're already being shown in the list now. 

So I think the duplicate resolution thing is more to do with the Nvidia driver and the multiple resolutions could be providing different options like color depth, refresh rate, etc. One day I'll look into this with an nvidia card I have laying around. 


Anyway, this should be fixed in the the next version. Next version will also include some other bug fixes too.
