### ISSUE TITLE
When removing a card from the deck and re-adding it, chest information is not updated.

### ISSUE THREAD

**Issue by rjoken** [suicvne/DOR_Remake#6]
![image](https://user-images.githubusercontent.com/17675149/118379058-d1581300-b5cf-11eb-8177-53ffd0b90cd6.png)
![image](https://user-images.githubusercontent.com/17675149/118379089-1419eb00-b5d0-11eb-93c2-84631c9cc218.png)
[Player.log](https://github.com/suicvne/DOR_Remake/files/6488325/Player.log)

When the card is added back into the deck, it is still displayed as "lit up" as though the card is still in the chest (card is actually added to the deck, though, but it's darkened in the deck).
The counter for chest/A/B/C is not updated on the chest side, and it is shown on the deck side as though there is still a copy in the chest. 
There is also a blank space in the deck list where the card was when I removed it (when re-adding, the card is added to the bottom, but the blank space remains.
If I make another space in my deck, I can "add" a duplicate copy of the card that appears in my chest into my deck (that I don't own). The card counter for the deck I am adding to increments, but it doesn't seem as though there are multiple copies in the deck after all.

I will include this in the same issue since it's deck edit related: when I change columns and start scrolling, I am returned to the top of the list, which is quite impractical.

Also, I am not sure if it is possible to view "special info" yet, but I can't seem to figure it out.

I can provide a video if this explanation is not clear enough :)

Additional information:
Client version: 0.6.8.2a win x86_64
OS: Windows 7 Ultimate x86_64
Specs: Ryzen 5 1400, nVidia GTX 950, 32gb ram

**Comment by suicvne** [comment]
There's a few different issues at play here:
```
When the card is added back into the deck, it is still displayed as "lit up" as though the card is still in the chest (card is actually added to the deck, though, but it's darkened in the deck).
The counter for chest/A/B/C is not updated on the chest side, and it is shown on the deck side as though there is still a copy in the chest.
```

Potential fix would be to trigger a refresh on the chest side when this happens. The card counts are being updated internally but the UI is not refreshing. Refreshing have to update the full list either so it won't be a heavy operation. Both lists you see in the screenshots only have about 10 or so items in them total, i just keep track of where in the list I am and read the next slots after that for each item. Initially, I was just lazily rendering all 800+ cards (at first, 150 which was fine but I wasnt happy) in the chest side as their own individually scroll items. Even though they're not displayed, this used a lot of memory. However, the list offsetting method does have some quirks that I havent spent much time on to overcome yet. 

```
There is also a blank space in the deck list where the card was when I removed it (when re-adding, the card is added to the bottom, but the blank space remains.
```
The blank spots in the lists are a problem that I need to look into. Well, its technically a quirk of the fact that at their core: Decks are just dumb arrays. Literally, there's some minor complexity due to the fact that decks are represented as ScriptableObjects in the editor but the class looks something like this:

```csharp
public class SerializedDeck : ScriptableObject
{
    [SerializeField] DORCard _DeckLeader;
    [SerializeField] DORCard[] _Deck;
}
```

So when a card is removed in the middle of the list, the UI is simply displaying what it sees in the array. When card 34 is removed, there's a blank spot at 34. My solution to this is to sort the array after we update it so the null spots end up at the end. One of those many tweaks that need to be added haha.

```
I will include this in the same issue since it's deck edit related: when I change columns and start scrolling, I am returned to the top of the list, which is quite impractical.
```
Yup, I agree it's pretty dumb. The DeckEditor doesn't integrate at all with my fancy new UI system and I only use one internal selection index. I may just take the easy route and store a second selection index for the Deck view side and make the one I have already for the chest view side. 

```
Also, I am not sure if it is possible to view "special info" yet, but I can't seem to figure it out.
```
Not yet, another tweak I have to make. You can't *technically* focus on the CardInfoController on either sides yet.

**Comment by suicvne** [comment]
Ok, good news.

```
When the card is added back into the deck, it is still displayed as "lit up" as though the card is still in the chest (card is actually added to the deck, though, but it's darkened in the deck).
The counter for chest/A/B/C is not updated on the chest side, and it is shown on the deck side as though there is still a copy in the chest.
```

Fixed!

```
There is also a blank space in the deck list where the card was when I removed it (when re-adding, the card is added to the bottom, but the blank space remains.
```

Also fixed!

```
I will include this in the same issue since it's deck edit related: when I change columns and start scrolling, I am returned to the top of the list, which is quite impractical.
```

This is fixed also!


But.....
```
Also, I am not sure if it is possible to view "special info" yet, but I can't seem to figure it out.
```

This one: not yet. I will make a separate issue for this to track it but I'm moving onto other issues now. 

As always, this issue will close once the tweaks I *did* make above have made it into a public version.
